package com.example.mydrugpal.model;

import com.google.firebase.Timestamp;

/**
 * An item found in the intake diary
 * @author Megan Brock, Alicia Wong
 */
public class IntakeDiaryItem {

    private String id;
    private String name;
    private String type;
    private String dose;
    private Timestamp dateTime;

    /**
     * constructor for each intake diary item
     * @param id autogenerated from database
     * @param name substance name
     * @param type category of substance
     * @param dose the number of doses taken
     * @param dateTime the date and time of the entry as a timestamp object
     */

    public IntakeDiaryItem(String id, String name, String type, String dose, Timestamp dateTime) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.dose = dose;
        this.dateTime = dateTime;
    }

    /**
     * returns substance ID
     * @return substance ID
     */
    public String getId() {
        return id;
    }

    /**
     * sets
     * @param id autogenerated from Database
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * returns dose taken
     * @return amount of substance taken
     */
    public String getDose() {
        return dose;
    }

    /**
     * set amount of substance taken
     * @param dose amount of substance taken
     */

    public void setDose(String dose) {
        this.dose = dose;
    }

    /**
     * returns the type of substance
     * @return type of substance
     */
    public String getType() {
        return type;
    }

    /**
     * set type of substance
     * @param type type of substance
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * returns substance name
     * @return substance name
     */
    public String getName() {
        return name;
    }

    /**
     * set substance name
     * @param name substance name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * gets the date and time the entry was made
     * @return date and time of entry
     */
    public Timestamp getDateTime() {
        return dateTime;
    }

}
